
%% Age-specific Survival Rates
s    = data.s;
s_cf = data.s_cf;
s0   = data.s0;
s0_cf= data.s0_cf;

%% Time Path Survival Cohort 00-01 - Cohort 10-14 
figure(1); clf;
plot(year, s0(1,:),'-+','color', [0.8 0 0.3],...
    'MarkerFaceColor', [0.6 0 0.3], 'MarkerSize',3,'linewidth',1.5)
hold on;
plot(year, s(1,:),'-s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(2,:),'-*', 'color', [0.8 0 0.6],...
    'MarkerFaceColor', [0.8 0 0.6], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(3,:),'-^', 'color', [0 0.6 0.6],...
      'MarkerFaceColor',[0 0.6 0.6], 'MarkerSize',3,'linewidth',1.5)

plot(year, s0_cf(1,:),':+','color', [0.6 0 0.3],...
    'MarkerFaceColor', [0.6 0 0.3], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(1,:),':s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(2,:),':*', 'color', [0.8 0 0.6],...
    'MarkerFaceColor', [0.8 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(3,:),':^', 'color', [0 0.6 0.6],...
      'MarkerFaceColor',[0 0.6 0.6], 'MarkerSize',3,'linewidth',2)

xlabel('Year','Interpreter','latex','FontSize',15)
ylabel('Survival rate','Interpreter','latex','FontSize',15)
legend('Actual cohort 0-1','Actual cohort 1-4','Actual cohort 5',...
       'Actual cohort 10','Counterfactual cohort 0-1',...
       'Counterfactual cohort 1-4','Counterfactual cohort 5',...
       'Counterfactual cohort 10','Interpreter','latex','FontSize',...
        10,'location','southeast','numcolumns',2);

% Auto-formatting for ticks
ylim([0.6, 1.01]);
set(gca, 'YTickMode', 'auto');
ytickformat('%.2f');
box on;
grid off;
hold off; 
set(gcf, 'WindowStyle', 'normal');
exportgraphics(gcf,"Graphs/Sur1.pdf"); 

%% Time Path Survival Cohort 15-19 - Cohort 30-34  
figure(2); clf;
plot(year, s(4,:),'-+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',1.5)
hold on;
plot(year, s(5,:),'-s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(6,:),'-*', 'color', [0.6 0 0],...
    'MarkerFaceColor', [0.6 0 0], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(7,:),'-^', 'color', [0 0.5 0],...
      'MarkerFaceColor',[0 0.5 0], 'MarkerSize',3,'linewidth',1.5)
  
plot(year, s_cf(4,:),':+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(5,:),':s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(6,:),':*', 'color', [0.6 0 0],...
    'MarkerFaceColor', [0.6 0 0], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(7,:),':^', 'color', [0 0.5 0],...
      'MarkerFaceColor',[0 0.5 0], 'MarkerSize',3,'linewidth',2)

xlabel('Year','Interpreter','latex','FontSize',15)
ylabel('Survival rate','Interpreter','latex','FontSize',15)
legend('Actual cohort 15','Actual cohort 20','Actual cohort 25',...
    'Actual cohort 30','Counterfactual cohort 15',...
    'Counterfactual cohort 20','Counterfactual cohort 25',...
    'Counterfactual cohort 30','Interpreter','latex','FontSize',10,....
    'location','southeast','numcolumns',2);

% Auto-formatting for ticks
ylim([0.68, 1.01]);
set(gca, 'YTickMode', 'auto');
ytickformat('%.2f');
box on;
grid off;
hold off; 
set(gcf, 'WindowStyle', 'normal');
exportgraphics(gcf,"Graphs/Sur2.pdf");

%% Time Path Survival Rate Cohort 35-39 - Cohort 50-54  
figure(3); clf;
plot(year, s(8,:),'-+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',1.5)
hold on
plot(year, s(9,:),'-s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(10,:),'-*', 'color', [0.4 0 0],...
    'MarkerFaceColor', [0.4 0 0], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(11,:),'-^', 'color', [0 0.4 0],...
      'MarkerFaceColor',[0 0.4 0], 'MarkerSize',3,'linewidth',1.5)
  
plot(year, s_cf(8,:),':+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(9,:),':s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(10,:),':*', 'color', [0.4 0 0],...
    'MarkerFaceColor', [0.4 0 0], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(11,:),':^', 'color', [0 0.4 0],...
      'MarkerFaceColor',[0 0.4 0], 'MarkerSize',3,'linewidth',2)

xlabel('Year','Interpreter','latex','FontSize',15)
ylabel('Survival rate','Interpreter','latex','FontSize',15)
legend('Actual cohort 35','Actual cohort 40','Actual cohort 45',...
    'Actual cohort 50', 'Counterfactual cohort 35',...
    'Counterfactual cohort 40','Counterfactual cohort 45',...
    'Counterfactual cohort 50','Interpreter','latex','FontSize',...
        10,'location','northwest','numcolumns',2);

% Auto-formatting for ticks
ylim([0.799, 1.02]);
set(gca, 'YTickMode', 'auto');
ytickformat('%.2f');
box on;
grid off;
hold off; 
set(gcf, 'WindowStyle', 'normal');
exportgraphics(gcf,"Graphs/Sur3.pdf");

%% Time Path Survival Cohort 55-59 - Cohort 70-74   
figure(4); clf;
plot(year, s(12,:),'-+','color', [0.5 0 0.5],...
    'MarkerFaceColor', [0.5 0 0.5], 'MarkerSize',3,'linewidth',1.5)
hold on
plot(year, s(13,:),'-s', 'color', [0 0.5 0.6],...
    'MarkerFaceColor', [0 0.5 0.6], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(14,:),'-*', 'color', [0.5 0 0],...
    'MarkerFaceColor', [0.5 0 0], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(15,:),'-^', 'color', [0 0.4 0],...
      'MarkerFaceColor',[0 0.4 0], 'MarkerSize',3,'linewidth',1.5)
  
plot(year, s_cf(12,:),':+','color', [0.5 0 0.5],...
    'MarkerFaceColor', [0.5 0 0.5], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(13,:),':s', 'color', [0 0.5 0.6],...
    'MarkerFaceColor', [0 0.5 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(14,:),':*', 'color', [0.5 0 0],...
    'MarkerFaceColor', [0.5 0 0], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(15,:),':^', 'color', [0 0.4 0],...
      'MarkerFaceColor',[0 0.4 0], 'MarkerSize',3,'linewidth',2)

xlabel('Year','Interpreter','latex','FontSize',15)
ylabel('Survival rate','Interpreter','latex','FontSize',15)
legend('Actual cohort 55','Actual cohort 60','Actual cohort 65',...
       'Actual cohort 70','Counterfactual cohort 55','Counterfactual cohort 60',...
       'Counterfactual cohort 65','Counterfactual cohort 70',...
       'Interpreter','latex','FontSize',...
        10,'location','southeast','numcolumns',2);

% Auto-formatting for ticks
ylim([0.42, 0.96]);
set(gca, 'YTickMode', 'auto');
ytickformat('%.2f');
box on;
grid off;
hold off; 
set(gcf, 'WindowStyle', 'normal');
exportgraphics(gcf,"Graphs/Sur4.pdf");

%% Time Path Survival Cohort 75-79 - Cohort 95-99   
figure(5); clf; 
plot(year, s(16,:),'-+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',1.5)
hold on
plot(year, s(17,:),'-s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(18,:),'-*', 'color', [0.6 0 0],...
    'MarkerFaceColor', [0.6 0 0], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(19,:),'-^', 'color', [0.5 0.5 0],...
      'MarkerFaceColor',[0.5 0.5 0], 'MarkerSize',3,'linewidth',1.5)
plot(year, s(20,:),'-+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',1.5)

plot(year, s_cf(16,:),':+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(17,:),':s', 'color', [0 0 0.6],...
    'MarkerFaceColor', [0 0 0.6], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(18,:),':*', 'color', [0.6 0 0],...
    'MarkerFaceColor', [0.6 0 0], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(19,:),':^', 'color', [0.5 0.5 0],...
      'MarkerFaceColor',[0 0.5 0], 'MarkerSize',3,'linewidth',2)
plot(year, s_cf(20,:),':+','color', [0.6 0 0.6],...
    'MarkerFaceColor', [0.6 0 0.6], 'MarkerSize',3,'linewidth',2)

xlabel('Year','Interpreter','latex','FontSize',15)
ylabel('Survival rate','Interpreter','latex','FontSize',15)
legend('Actual cohort 75','Actual cohort 80','Actual cohort 85',...
    'Actual cohort 90','Actual cohort 95','Counterfactual cohort 75',...
    'Counterfactual cohort 80','Counterfactual cohort 85',...
    'Counterfactual cohort 90','Counterfactual cohort 95',...
    'Interpreter','latex','FontSize',10,'location','Northwest','numcolumns',2);

% Auto-formatting for ticks
ylim([0.04, 0.78]);
set(gca, 'YTickMode', 'auto');
ytickformat('%.2f');
box on;
grid off;
hold off; 
set(gcf, 'WindowStyle', 'normal');
exportgraphics(gcf,"Graphs/Sur5.pdf");
